services:
  moodweave-ai:
    image: moodweave-ai:latest
    container_name: moodweave-ai
    restart: always
    env_file:
      - ../../../.env
    networks:
      - edge

networks:
  edge:
    external: true
