services:
  moodweave-core:
    image: moodweave-core:latest
    container_name: moodweave-core
    restart: always
    env_file:
      - ../../.env
    networks:
      - edge

networks:
  edge:
    external: true
